---@module "lazy"
---@type LazySpec
return {
  'WhoIsSethDaniel/mason-tool-installer.nvim',
  dependencies = {
    'williamboman/mason.nvim',
    'williamboman/mason-lspconfig.nvim',
  },
  ft = {
    'css',
    'fish',
    'html',
    'javascript',
    'json',
    'lua',
    'make',
    'markdown',
    'python',
    'sh',
    'toml',
    'typescript',
    'xml',
    'yaml',
  },
  cmd = 'Mason',
  opts = {
    auto_update = true,
    ensure_installed = {
      'bash-debug-adapter',
      'bashls',
      'checkmake',
      'debugpy',
      'eslint_d',
      'fish-lsp',
      'html',
      'jsonlint',
      'jsonls',
      'lemminx',
      'lua_ls',
      'markdownlint',
      'marksman',
      'prettier',
      'pyright',
      'ruff',
      'shellcheck',
      'shfmt',
      'stylua',
      'taplo',
      'ts_ls',
      'xmlformatter',
      'yamlfmt',
      'yamllint',
      'yamlls',
    },
  },
}
