---@param p table palette
---@return table
local function plugins(p)
  return {
    -- blink.cmp
    BlinkCmpMenu = { fg = p.fg0, bg = p.bg1 },
    BlinkCmpMenuBorder = { fg = p.fg3, bg = p.bg1 },
    BlinkCmpMenuSelection = { bg = p.sel, bold = true },
    BlinkCmpScrollBarThumb = { bg = p.fg3 },
    BlinkCmpScrollBarGutter = { bg = p.bg2 },
    BlinkCmpLabel = { fg = p.fg0 },
    BlinkCmpLabelDeprecated = { fg = p.fg3, strikethrough = true },
    BlinkCmpLabelMatch = { fg = p.accent, bold = true },
    BlinkCmpLabelDetail = { fg = p.fg2 },
    BlinkCmpLabelDescription = { fg = p.fg2 },
    BlinkCmpKind = { fg = p.fg2 },
    BlinkCmpKindText = { fg = p.fg1 },
    BlinkCmpKindMethod = { fg = p.accent },
    BlinkCmpKindFunction = { fg = p.accent },
    BlinkCmpKindConstructor = { fg = p.blue },
    BlinkCmpKindField = { fg = p.fg0 },
    BlinkCmpKindVariable = { fg = p.fg0 },
    BlinkCmpKindClass = { fg = p.blue },
    BlinkCmpKindInterface = { fg = p.blue },
    BlinkCmpKindModule = { fg = p.blue },
    BlinkCmpKindProperty = { fg = p.fg0 },
    BlinkCmpKindUnit = { fg = p.purple },
    BlinkCmpKindValue = { fg = p.purple },
    BlinkCmpKindEnum = { fg = p.blue },
    BlinkCmpKindKeyword = { fg = p.accent2 },
    BlinkCmpKindSnippet = { fg = p.green },
    BlinkCmpKindColor = { fg = p.purple },
    BlinkCmpKindFile = { fg = p.blue },
    BlinkCmpKindReference = { fg = p.blue },
    BlinkCmpKindFolder = { fg = p.blue },
    BlinkCmpKindEnumMember = { fg = p.purple },
    BlinkCmpKindConstant = { fg = p.purple },
    BlinkCmpKindStruct = { fg = p.blue },
    BlinkCmpKindEvent = { fg = p.accent2 },
    BlinkCmpKindOperator = { fg = p.fg1 },
    BlinkCmpKindTypeParameter = { fg = p.blue },
    BlinkCmpDoc = { fg = p.fg0, bg = p.bg0 },
    BlinkCmpDocBorder = { fg = p.fg3, bg = p.bg0 },
    BlinkCmpDocSeparator = { fg = p.fg3, bg = p.bg0 },
    BlinkCmpDocCursorLine = { bg = p.bg5 },
    BlinkCmpSignatureHelp = { fg = p.fg0, bg = p.bg0 },
    BlinkCmpSignatureHelpBorder = { fg = p.fg3, bg = p.bg0 },
    BlinkCmpSignatureHelpActiveParameter = { fg = p.accent, bold = true },
    BlinkCmpGhostText = { fg = p.fg3, italic = true },
    BlinkCmpSource = { fg = p.fg2 },

    -- vim-matchup
    MatchWord = { bg = p.bg5 },
    MatchWordCur = { bg = p.bg5 },
    MatchParenCur = { fg = p.accent, bold = true, underline = true },

    -- indent-blankline
    IblIndent = { fg = p.bg5 },
    IblScope = { fg = p.fg3 },
    IblWhitespace = { fg = p.bg5 },

    -- render-markdown
    RenderMarkdownH1 = { fg = p.accent, bold = true },
    RenderMarkdownH2 = { fg = p.accent2, bold = true },
    RenderMarkdownH3 = { fg = p.yellow, bold = true },
    RenderMarkdownH4 = { fg = p.blue, bold = true },
    RenderMarkdownH5 = { fg = p.green, bold = true },
    RenderMarkdownH6 = { fg = p.purple, bold = true },
    RenderMarkdownH1Bg = { bg = p.bg4 },
    RenderMarkdownH2Bg = { bg = p.bg4 },
    RenderMarkdownH3Bg = { bg = p.bg4 },
    RenderMarkdownH4Bg = { bg = p.bg4 },
    RenderMarkdownH5Bg = { bg = p.bg4 },
    RenderMarkdownH6Bg = { bg = p.bg4 },
    RenderMarkdownCode = { bg = p.bg2 },
    RenderMarkdownCodeInline = { fg = p.green, bg = p.bg2 },
    RenderMarkdownBullet = { fg = p.accent2 },
    RenderMarkdownQuote = { fg = p.fg2, italic = true },
    RenderMarkdownLink = { fg = p.blue, underline = true },
    RenderMarkdownMath = { fg = p.blue },
    RenderMarkdownSign = { fg = p.fg2, bg = p.bg3 },
    RenderMarkdownChecked = { fg = p.green },
    RenderMarkdownUnchecked = { fg = p.fg3 },
    RenderMarkdownTableHead = { fg = p.accent, bold = true },
    RenderMarkdownTableRow = { fg = p.fg0 },
    RenderMarkdownTableFill = { fg = p.fg3 },
    RenderMarkdownDash = { fg = p.fg3 },
    RenderMarkdownError = { fg = p.red },
    RenderMarkdownWarn = { fg = p.yellow },
    RenderMarkdownInfo = { fg = p.blue },
    RenderMarkdownHint = { fg = p.green },
    RenderMarkdownSuccess = { fg = p.green },

    -- oil.nvim
    OilDir = { fg = p.blue },
    OilFile = { fg = p.fg0 },
    OilLink = { fg = p.purple },
    OilLinkTarget = { fg = p.purple, italic = true },
    OilSocket = { fg = p.accent2 },
    OilOrphanLink = { fg = p.red },
    OilOrphanLinkTarget = { fg = p.red, italic = true },
    OilCreate = { fg = p.green },
    OilDelete = { fg = p.red },
    OilMove = { fg = p.accent2 },
    OilCopy = { fg = p.yellow },
    OilChange = { fg = p.blue },
    OilPermissionNone = { fg = p.fg3 },
    OilPermissionRead = { fg = p.yellow },
    OilPermissionWrite = { fg = p.red },
    OilPermissionExecute = { fg = p.green },
    OilTypeDir = { fg = p.blue },
    OilTypeFile = { fg = p.fg2 },
    OilTypeLink = { fg = p.purple },
    OilTypeSocket = { fg = p.accent2 },

    -- gitsigns
    GitSignsAdd = { fg = p.green },
    GitSignsChange = { fg = p.yellow },
    GitSignsDelete = { fg = p.red },
    GitSignsTopDelete = { fg = p.red },
    GitSignsChangeDelete = { fg = p.accent },
    GitSignsUntracked = { fg = p.fg3 },
    GitSignsAddNr = { link = 'GitSignsAdd' },
    GitSignsChangeNr = { link = 'GitSignsChange' },
    GitSignsDeleteNr = { link = 'GitSignsDelete' },
    GitSignsAddLn = { bg = p.diff_add },
    GitSignsChangeLn = { bg = p.diff_change },
    GitSignsDeleteLn = { bg = p.diff_del },
    GitSignsAddPreview = { bg = p.diff_add },
    GitSignsDeletePreview = { bg = p.diff_del },
    GitSignsCurrentLineBlame = { fg = p.fg3, italic = true },

    -- neogit
    NeogitBranch = { fg = p.accent },
    NeogitRemote = { fg = p.blue },
    NeogitHunkHeader = { fg = p.fg0, bg = p.bg4, bold = true },
    NeogitHunkHeaderHighlight = { fg = p.accent, bg = p.bg5, bold = true },
    NeogitDiffAdd = { fg = p.green, bg = p.diff_add },
    NeogitDiffDelete = { fg = p.red, bg = p.diff_del },
    NeogitDiffContext = { fg = p.fg1, bg = p.bg3 },
    NeogitDiffContextHighlight = { fg = p.fg0, bg = p.bg4 },
    NeogitDiffAddHighlight = { fg = p.green, bg = p.diff_add, bold = true },
    NeogitDiffDeleteHighlight = { fg = p.red, bg = p.diff_del, bold = true },
    NeogitChangeModified = { fg = p.yellow },
    NeogitChangeAdded = { fg = p.green },
    NeogitChangeDeleted = { fg = p.red },
    NeogitChangeRenamed = { fg = p.purple },
    NeogitChangeNewFile = { fg = p.green },
    NeogitChangeUpdated = { fg = p.blue },
    NeogitChangeCopied = { fg = p.accent2 },
    NeogitChangeUnmerged = { fg = p.accent },
    NeogitUnpushedTo = { fg = p.accent },
    NeogitUnpulledFrom = { fg = p.blue },
    NeogitSectionHeader = { fg = p.accent, bold = true },
    NeogitStash = { fg = p.fg1 },
    NeogitStashEntry = { fg = p.fg0 },
    NeogitObjectId = { fg = p.fg3 },
    NeogitGraphBlue = { fg = p.blue },
    NeogitGraphRed = { fg = p.red },
    NeogitGraphWhite = { fg = p.fg0 },
    NeogitGraphGray = { fg = p.fg3 },
    NeogitGraphGreen = { fg = p.green },
    NeogitGraphYellow = { fg = p.yellow },
    NeogitGraphOrange = { fg = p.accent },
    NeogitGraphPurple = { fg = p.purple },
    NeogitGraphBoldBlue = { fg = p.blue, bold = true },
    NeogitGraphBoldRed = { fg = p.red, bold = true },
    NeogitGraphBoldWhite = { fg = p.fg0, bold = true },
    NeogitGraphBoldGray = { fg = p.fg3, bold = true },
    NeogitGraphBoldGreen = { fg = p.green, bold = true },
    NeogitGraphBoldYellow = { fg = p.yellow, bold = true },
    NeogitGraphBoldOrange = { fg = p.accent, bold = true },
    NeogitGraphBoldPurple = { fg = p.purple, bold = true },

    -- diffview
    DiffviewFilePanelRootPath = { fg = p.fg3 },
    DiffviewFilePanelTitle = { fg = p.accent, bold = true },
    DiffviewFilePanelCounter = { fg = p.fg2 },
    DiffviewFilePanelFileName = { fg = p.fg0 },
    DiffviewFilePanelInsertions = { fg = p.green },
    DiffviewFilePanelDeletions = { fg = p.red },
    DiffviewFilePanelConflicts = { fg = p.yellow },
    DiffviewFolderName = { fg = p.blue },
    DiffviewFolderSign = { fg = p.fg3 },
    DiffviewStatusAdded = { fg = p.green },
    DiffviewStatusUntracked = { fg = p.fg3 },
    DiffviewStatusModified = { fg = p.yellow },
    DiffviewStatusRenamed = { fg = p.purple },
    DiffviewStatusCopied = { fg = p.accent2 },
    DiffviewStatusTypeChange = { fg = p.blue },
    DiffviewStatusUnmerged = { fg = p.accent },
    DiffviewStatusUnknown = { fg = p.red },
    DiffviewStatusDeleted = { fg = p.red },
    DiffviewStatusBroken = { fg = p.red, bold = true },
    DiffviewStatusIgnored = { fg = p.fg3 },

    -- mason
    MasonHeader = { fg = p.bg3, bg = p.accent, bold = true },
    MasonHeaderSecondary = { fg = p.bg3, bg = p.accent2, bold = true },
    MasonHighlight = { fg = p.accent },
    MasonHighlightBlock = { fg = p.bg3, bg = p.accent },
    MasonHighlightBlockBold = { fg = p.bg3, bg = p.accent, bold = true },
    MasonHighlightSecondary = { fg = p.accent2 },
    MasonHighlightBlockSecondary = { fg = p.bg3, bg = p.accent2 },
    MasonHighlightBlockBoldSecondary = { fg = p.bg3, bg = p.accent2, bold = true },
    MasonMuted = { fg = p.fg2 },
    MasonMutedBlock = { fg = p.fg2, bg = p.bg4 },
    MasonMutedBlockBold = { fg = p.fg2, bg = p.bg4, bold = true },
    MasonError = { fg = p.red },
    MasonWarning = { fg = p.yellow },
    MasonLink = { fg = p.blue, underline = true },

    -- mini.statusline
    MiniStatuslineModeNormal = { fg = p.bg3, bg = p.fg2, bold = true },
    MiniStatuslineModeInsert = { fg = p.bg3, bg = p.green, bold = true },
    MiniStatuslineModeVisual = { fg = p.bg3, bg = p.accent2, bold = true },
    MiniStatuslineModeReplace = { fg = p.bg3, bg = p.red, bold = true },
    MiniStatuslineModeCommand = { fg = p.bg3, bg = p.yellow, bold = true },
    MiniStatuslineModeOther = { fg = p.bg3, bg = p.blue, bold = true },
    MiniStatuslineDevinfo = { fg = p.fg1, bg = p.bg4 },
    MiniStatuslineFilename = { fg = p.fg1, bg = p.bg2 },
    MiniStatuslineFileinfo = { fg = p.fg1, bg = p.bg4 },
    MiniStatuslineInactive = { fg = p.fg3, bg = p.bg1 },

    -- mini.icons
    MiniIconsAzure = { fg = p.cyan },
    MiniIconsBlue = { fg = p.blue },
    MiniIconsCyan = { fg = p.cyan },
    MiniIconsGreen = { fg = p.green },
    MiniIconsGrey = { fg = p.fg2 },
    MiniIconsOrange = { fg = p.accent },
    MiniIconsPurple = { fg = p.purple },
    MiniIconsRed = { fg = p.red },
    MiniIconsWhite = { fg = p.fg0 },
    MiniIconsYellow = { fg = p.yellow },

    -- treesitter-context
    TreesitterContext = { bg = p.bg2 },
    TreesitterContextLineNumber = { fg = p.fg3, bg = p.bg2 },
    TreesitterContextBottom = { underline = true, sp = p.fg3 },
    TreesitterContextLineNumberBottom = { underline = true, sp = p.fg3 },
    TreesitterContextSeparator = { fg = p.fg3 },

    -- which-key
    WhichKey = { fg = p.accent },
    WhichKeyGroup = { fg = p.blue },
    WhichKeyDesc = { fg = p.fg0 },
    WhichKeySeparator = { fg = p.fg3 },
    WhichKeyValue = { fg = p.fg2 },
    WhichKeyBorder = { fg = p.fg3, bg = p.bg0 },
    WhichKeyNormal = { bg = p.bg0 },
    WhichKeyTitle = { fg = p.accent, bg = p.bg0, bold = true },

    -- trouble.nvim
    TroubleNormal = { fg = p.fg0, bg = p.bg1 },
    TroubleNormalNC = { fg = p.fg0, bg = p.bg1 },
    TroubleCount = { fg = p.accent, bold = true },
    TroubleIconError = { fg = p.red },
    TroubleIconWarning = { fg = p.yellow },
    TroubleIconInformation = { fg = p.blue },
    TroubleIconHint = { fg = p.green },
    TroubleIconOther = { fg = p.fg2 },
    TroubleIconDirectory = { fg = p.blue },
    TroubleIconFile = { fg = p.fg0 },
    TroubleText = { fg = p.fg0 },
    TroubleTextError = { fg = p.red },
    TroubleTextWarning = { fg = p.yellow },
    TroubleTextInformation = { fg = p.blue },
    TroubleTextHint = { fg = p.green },
    TroubleCode = { fg = p.fg2 },
    TroubleSource = { fg = p.fg2 },
    TroublePos = { fg = p.fg3 },
    TroubleIndent = { fg = p.fg3 },
    TroubleIndentFoldOpen = { fg = p.accent },
    TroubleIndentFoldClosed = { fg = p.fg3 },
    TroubleIndentWs = { fg = p.fg3 },
    TroubleIndentTop = { fg = p.fg3 },
    TroubleIndentMiddle = { fg = p.fg3 },
    TroubleIndentLast = { fg = p.fg3 },
    TroubleAncestry = { fg = p.fg3 },
    TroubleBasename = { fg = p.fg0, bold = true },
    TroubleDirectory = { fg = p.blue },
    TroubleDirname = { fg = p.blue },
    TroubleFilename = { fg = p.fg0 },
    TroublePreview = { bg = p.bg4 },

    -- fzf-lua
    FzfLuaNormal = { fg = p.fg0, bg = p.bg1 },
    FzfLuaBorder = { fg = p.fg3, bg = p.bg1 },
    FzfLuaTitle = { fg = p.accent, bg = p.bg1, bold = true },
    FzfLuaPreviewNormal = { fg = p.fg0, bg = p.bg0 },
    FzfLuaPreviewBorder = { fg = p.fg3, bg = p.bg0 },
    FzfLuaPreviewTitle = { fg = p.accent2, bg = p.bg0, bold = true },
    FzfLuaCursor = { link = 'Cursor' },
    FzfLuaCursorLine = { link = 'CursorLine' },
    FzfLuaCursorLineNr = { link = 'CursorLineNr' },
    FzfLuaSearch = { link = 'Search' },
    FzfLuaScrollBorderEmpty = { fg = p.fg3, bg = p.bg1 },
    FzfLuaScrollBorderFull = { fg = p.accent, bg = p.bg1 },
    FzfLuaScrollFloatEmpty = { bg = p.bg2 },
    FzfLuaScrollFloatFull = { bg = p.accent },
    FzfLuaHelpNormal = { fg = p.fg0, bg = p.bg0 },
    FzfLuaHelpBorder = { fg = p.fg3, bg = p.bg0 },
    FzfLuaHeaderBind = { fg = p.accent2 },
    FzfLuaHeaderText = { fg = p.blue },
    FzfLuaPathColNr = { fg = p.fg3 },
    FzfLuaPathLineNr = { fg = p.fg3 },
    FzfLuaBufName = { fg = p.fg1 },
    FzfLuaBufNr = { fg = p.fg3 },
    FzfLuaBufFlagCur = { fg = p.accent },
    FzfLuaBufFlagAlt = { fg = p.accent2 },
    FzfLuaTabTitle = { fg = p.accent, bold = true },
    FzfLuaTabMarker = { fg = p.accent2 },
    FzfLuaDirIcon = { fg = p.blue },
    FzfLuaLiveSym = { fg = p.accent2 },

    -- claudecode.nvim
    ClaudeCodeDiffAdd = { bg = p.diff_add },
    ClaudeCodeDiffDelete = { bg = p.diff_del },
    ClaudeCodeDiffChange = { bg = p.diff_change },
    ClaudeCodeDiffText = { bg = p.diff_text },

    -- NvimTree
    NvimTreeNormal = { fg = p.fg0, bg = p.bg1 },
    NvimTreeNormalNC = { fg = p.fg0, bg = p.bg1 },
    NvimTreeWinSeparator = { fg = p.bg4, bg = p.bg1 },
    NvimTreeEndOfBuffer = { fg = p.bg1 },
    NvimTreeCursorLine = { bg = p.bg4 },
    NvimTreeRootFolder = { fg = p.accent, bold = true },
    NvimTreeFolderName = { fg = p.blue },
    NvimTreeFolderIcon = { fg = p.blue },
    NvimTreeOpenedFolderName = { fg = p.blue, bold = true },
    NvimTreeEmptyFolderName = { fg = p.fg3 },
    NvimTreeSymlinkFolderName = { fg = p.purple },
    NvimTreeFileName = { fg = p.fg0 },
    NvimTreeOpenedFile = { fg = p.fg0, bold = true },
    NvimTreeModifiedFile = { fg = p.yellow },
    NvimTreeSpecialFile = { fg = p.accent2 },
    NvimTreeSymlink = { fg = p.purple },
    NvimTreeIndentMarker = { fg = p.fg3 },
    NvimTreeImageFile = { fg = p.purple },
    NvimTreeGitDirty = { fg = p.yellow },
    NvimTreeGitStaged = { fg = p.green },
    NvimTreeGitMerge = { fg = p.accent },
    NvimTreeGitRenamed = { fg = p.purple },
    NvimTreeGitNew = { fg = p.green },
    NvimTreeGitDeleted = { fg = p.red },
    NvimTreeGitIgnored = { fg = p.fg3 },
    NvimTreeDiagnosticErrorIcon = { fg = p.red },
    NvimTreeDiagnosticWarnIcon = { fg = p.yellow },
    NvimTreeDiagnosticInfoIcon = { fg = p.blue },
    NvimTreeDiagnosticHintIcon = { fg = p.green },

    -- lazy.nvim
    LazyNormal = { fg = p.fg0, bg = p.bg1 },
    LazyH1 = { fg = p.bg3, bg = p.accent, bold = true },
    LazyH2 = { fg = p.accent, bold = true },
    LazyButton = { fg = p.fg1, bg = p.bg4 },
    LazyButtonActive = { fg = p.bg3, bg = p.accent2, bold = true },
    LazyComment = { fg = p.fg2 },
    LazyCommit = { fg = p.fg3 },
    LazyCommitIssue = { fg = p.blue },
    LazyCommitScope = { fg = p.fg2, italic = true },
    LazyCommitType = { fg = p.accent2 },
    LazyDimmed = { fg = p.fg3 },
    LazyDir = { fg = p.blue },
    LazyProgressDone = { fg = p.accent },
    LazyProgressTodo = { fg = p.fg3 },
    LazyProp = { fg = p.fg2 },
    LazyReasonCmd = { fg = p.accent2 },
    LazyReasonEvent = { fg = p.yellow },
    LazyReasonFt = { fg = p.blue },
    LazyReasonImport = { fg = p.fg1 },
    LazyReasonKeys = { fg = p.accent },
    LazyReasonPlugin = { fg = p.purple },
    LazyReasonRuntime = { fg = p.fg2 },
    LazyReasonSource = { fg = p.green },
    LazyReasonStart = { fg = p.green },
    LazySpecial = { fg = p.accent },
    LazyTaskOutput = { fg = p.fg0 },
    LazyUrl = { fg = p.blue, underline = true },
    LazyValue = { fg = p.green },

    -- ccc.nvim
    CccFloatNormal = { link = 'NormalFloat' },
    CccFloatBorder = { link = 'FloatBorder' },
  }
end

return plugins
